default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myclass103_development

test:
  <<: *default
  database: myclass103_test

production:
  <<: *default
  database: myclass103_production
  username: myclass103
  password: <%= ENV['myclass103_DATABASE_PASSWORD'] %>
