# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56bb52c1c93004e27a0a28d0348f1a34395af85d346f8b340093bd357159bf1ddba9a34aec9abe3f43f8df645b0d4848a4a7f87f7c39a6e5a711dbe36d3d3455

test:
  secret_key_base: ac70aa9d178224ba2243fef9c6aa3b3f54437a71d0d99656d82f779f579d1d142cd0528edd96352ec71e15113f5f51bc21cbb8542fc12da09ec84b95bd0f0d3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
